name = "Dataset"
uuid = "5c01b14b-ab03-46ff-b164-14c663efdd9f"
authors = ["sl-solution <github.sl.solution@icloud.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
